project:
  type: website

website:
  title: "Mariia Atamaniuk"
  navbar:
    left:
      - href: index.qmd
        text: Serious CV
      - href: about.qmd
        text: Not serious CV

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    fontsize: 1.1em
    linestretch: 1.7

editor: visual

