project:
  type: website
  output-dir: docs

website:
  title: "Mariia Atamaniuk"
  navbar:
    left:
      - href: index.qmd
        text: Serious stuff
      - href: about.qmd
        text: About

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

